-- 北京市
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_110000;
-- 天津市
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_120000;
-- 河北省
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_130000;
-- 山西省
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_140000;
-- 内蒙古自治区
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_150000;
-- 黑龙江省
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_210000;
-- 吉林省
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_220000;
-- 辽宁省
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_230000;
-- 新疆维吾尔自治区
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_310000;
-- 甘肃省
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_320000;
-- 青海省
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_330000;
-- 宁夏回族自治区
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_340000;
-- 陕西省
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_350000;
-- 上海市
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_410000;
-- 山东省
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_420000;
-- 江苏省
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_430000;
-- 安徽省
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_440000;
-- 湖北省
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_450000;
-- 浙江省
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_460000;
-- 河南省
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_470000;
-- 湖南省
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_480000;
-- 广东省
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_510000;
-- 福建省
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_520000;
-- 广西壮族自治区
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_530000;
-- 海南省
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_540000;
-- 台湾省
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_550000;
-- 重庆市
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_610000;
-- 四川省
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_620000;
-- 云南省
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_630000;
-- 贵州省
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_640000;
-- 西藏自治区
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_650000;
-- 香港特别行政区
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_710000;
-- 澳门特别行政区
CREATE DATABASE IF NOT EXISTS ELECTRONIC_COMMERCE_720000;